# Generated by Django 5.2 on 2025-05-26 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.BigIntegerField(unique=True)),
                ('channel_name', models.CharField(max_length=255)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={                'verbose_name': 'Telegram Channel',
                'verbose_name_plural': 'Telegram Channels',
                'db_table': 'telegram_channels',
            },
        ),
        migrations.CreateModel(
            name='CrawlerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('DEBUG', 'Debug')], max_length=10)),
                ('message', models.TextField()),
                ('module', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('extra_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Crawler Log',
                'verbose_name_plural': 'Crawler Logs',
                'db_table': 'crawler_logs',
                'indexes': [models.Index(fields=['level'], name='crawler_log_level_573c36_idx'), models.Index(fields=['timestamp'], name='crawler_log_timesta_75a6f5_idx'), models.Index(fields=['module'], name='crawler_log_module_cbc47a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('message_text', models.TextField()),
                ('classification', models.CharField(choices=[('relevant', 'Relevant'), ('irrelevant', 'Irrelevant')], max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('extracted_links', models.JSONField(blank=True, null=True)),
                ('extracted_github_url', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crawler.telegramchannel')),
            ],
            options={                'verbose_name': 'Telegram Message',
                'verbose_name_plural': 'Telegram Messages',
                'db_table': 'telegram_messages',
            },
        ),
        migrations.CreateModel(
            name='ArchivedGithubUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archive_url', models.URLField(blank=True, max_length=500, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_urls', to='crawler.telegrammessage')),
            ],
            options={                'verbose_name': 'Archived GitHub URL',
                'verbose_name_plural': 'Archived GitHub URLs',
                'db_table': 'archived_github_urls',
            },
        ),
        migrations.CreateModel(
            name='DeletedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default='irrelevant', max_length=255)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_messages', to='crawler.telegramchannel')),
            ],
            options={
                'verbose_name': 'Deleted Message',
                'verbose_name_plural': 'Deleted Messages',
                'db_table': 'deleted_messages',
                'unique_together': {('message_id', 'channel')},
            },
        ),
        migrations.AddIndex(
            model_name='telegrammessage',
            index=models.Index(fields=['classification'], name='telegram_me_classif_338c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrammessage',
            index=models.Index(fields=['timestamp'], name='telegram_me_timesta_27f101_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrammessage',
            index=models.Index(fields=['message_id'], name='telegram_me_message_3ad64f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='telegrammessage',
            unique_together={('message_id', 'channel')},
        ),
        migrations.AlterUniqueTogether(
            name='archivedgithuburl',
            unique_together={('url', 'message')},
        ),
    ]
