# Generated by Django 5.2 on 2025-05-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_crawlersettings_crawlerstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, unique=True)),
                ('keyword_type', models.CharField(choices=[('security', 'Security'), ('vulnerability', 'Vulnerability'), ('exploit', 'Exploit'), ('domain', 'Domain'), ('other', 'Other')], default='other', max_length=20)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={                'verbose_name': 'Message Keyword',
                'verbose_name_plural': 'Message Keywords',
                'db_table': 'message_keywords',
                'indexes': [models.Index(fields=['keyword_type'], name='message_key_keyword_82195b_idx'), models.Index(fields=['is_active'], name='message_key_is_acti_1a5093_idx')],
            },
        ),
    ]
