# Generated by Django 5.2 on 2025-05-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_messagekeyword'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crawlersettings',
            options={'verbose_name': 'Crawler Setting', 'verbose_name_plural': 'Crawler Settings'},
        ),
        migrations.AlterModelOptions(
            name='crawlerstatus',
            options={'verbose_name': 'Crawler Status', 'verbose_name_plural': 'Crawler Statuses'},
        ),
        migrations.AlterModelOptions(
            name='deletedmessage',
            options={'verbose_name': 'Deleted Message', 'verbose_name_plural': 'Deleted Messages'},
        ),
        migrations.AlterField(
            model_name='crawlerstatus',
            name='status',
            field=models.CharField(choices=[('stopped', 'Stopped'), ('running', 'Running'), ('error', 'Error')], default='stopped', max_length=20),
        ),
        migrations.AlterField(
            model_name='messagekeyword',
            name='keyword_type',
            field=models.CharField(choices=[('security', 'Security'), ('vulnerability', 'Vulnerability'), ('exploit', 'Exploit'), ('domain', 'Domain'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='classification',
            field=models.CharField(choices=[('relevant', 'Relevant'), ('irrelevant', 'Irrelevant')], max_length=20),
        ),
    ]
