# Generated by Django 5.2.1 on 2025-05-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_alter_crawlersettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedgithuburl',
            name='archive_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='archivedgithuburl',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='classification',
            field=models.CharField(choices=[('relevant', 'Relevant'), ('irrelevant', 'Irrelevant')], max_length=255),
        ),
    ]
