# Generated by Django 5.2.1 on 2025-05-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_alter_archivedgithuburl_archive_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlerstatus',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crawlerstatus',
            name='last_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
